# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterApp' do

pod 'MagicalRecord/Shorthand'
pod 'STTwitter'
pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git', :tag => '1.0.0'

end
